### ISSUE TITLE
Bug caught by SWDiA5BY authors?

### ISSUE THREAD

**Issue by msoos** [niklasso/minisat#19]
Hey,

I see this diff in their code relative to MiniSat:

```
-           if (phase_saving > 1 || (phase_saving == 1 && c > trail_lim.last())) {
+           if (phase_saving > 1 || (phase_saving == 1) && c > trail_lim.last()) {
```

Is this something meaningful? I am completely out-of-track of MiniSat but I thought this might be a bug they caught?

**Comment by timrau** [comment]
The two lines are equivalent since `&&` operator has higher precedence.

**Comment by msoos** [comment]
True, but the question is -- did the authors mean it that way?

**Comment by msoos** [comment]
Let's close this, probably not important.
