### ISSUE TITLE
unexpected results running minisat on SATLIB benchmark tests

### ISSUE THREAD

**Issue by emasab** [niklasso/minisat#34]
Hi, I'm trying to benchmark another sat solver and I've tried to compare it to minisat

I'm using the benchmark set https://www.cs.ubc.ca/~hoos/SATLIB/Benchmarks/SAT/RND3SAT/uf20-91.tar.gz from

https://www.cs.ubc.ca/~hoos/SATLIB/benchm.html

they say that they're all satisfiable. I've compiled the master branch of minisat. At first it gives 

PARSE ERROR! Unexpected char: %

then if I remove that last row with the % character and i run with 

```bash
time for file in $(ls ~/Desktop/3SAT/uf20-91/); do cat ~/Desktop/3SAT/uf20-91/$file | grep -v '%' | build/release/bin/minisat -pre /dev/stdin /dev/stdout; done
```

I get all UNSATIFIABLE results like this:

```
WARNING: for repeatability, setting FPU to use double precision
============================[ Problem Statistics ]=============================
|                                                                             |
|  Number of variables:            20                                         |
|  Number of clauses:              91                                         |
|  Parse time:                   0.00 s                                       |
|  Simplification time:          0.00 s                                       |
|                                                                             |
UNSAT
===============================================================================
Solved by simplification
restarts              : 0
conflicts             : 0              (0 /sec)
decisions             : 0              (-nan % random) (0 /sec)
propagations          : 0              (0 /sec)
conflict literals     : 0              (-nan % deleted)
Memory used           : 5.94 MB
CPU time              : 0.000964 s

UNSATISFIABLE
```

whereas they should be all satifiable. I should be doing something wrong.

**Comment by liffiton** [comment]
I'm not quite sure what format those files are in, but the `%` isn't the only issue.  The line following the `%` appears to always be `0`.  In CNF, that is an empty clause, and empty clauses are not satisfiable.  Remove the `%` *and* the following line with just `0`, and the instances should become satisfiable (or at least the one I tested did).

**Comment by emasab** [comment]
Thanks for the check, that way it works correctly
