### ISSUE TITLE
Read-only file system

### ISSUE THREAD

**Issue by verifierlife** [niklasso/minisat#38]
@niklasso  @koengit 
I am using Mac OS Catalina to install minisat.
When I run the command " make install", I get the following errors:
`install -d /include/minisat                                                                                                             
install: mkdir /include: Read-only file system                                                                               
make: *** [install-headers] Error 71`

I has already tried for many times, but I failed.

**Comment by EcnuTengfei** [comment]
I think I has already solved it. This is a suggestion:
https://www.reddit.com/r/MacOS/comments/caiue5/macos_catalina_readonly_file_system_with_sip/

**Comment by verifierlife** [comment]
I think I has already solved it. 
This is a suggestion:
https://www.reddit.com/r/MacOS/comments/caiue5/macos_catalina_readonly_file_system_with_sip/

Only for Mac OS Catalina.
